engines:
  duplication:
    enabled: true
checks:
  similar-code:
  enabled: false
config:
  languages:
    - javascript
fixme:
  enabled: true
ratings:
  paths:
    - "/*.js"
    - "/**/*.js"
    - "/**/**/*.js"
exclude_patterns:
  - node_modules/
  - server/dummyData/
  - view/
  - public/