language: node_js
node_js:
 - "8.9.1"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
 - npm travis
after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report-coverage
  - CODECLIMATE_REPO_TOKEN=1aa8d6a29c0d4641f0b985f13d08c23cf20a25ea01988c1074fc5a26a43bb047 codeclimate-test-reporter < ./coverage/lcov.info
