const transformer = {};

transformer.transformResponse = (responseCode, responseText, payload) => {
  if (!payload) {
    payload = {};
  }

  return {
    responseCode,
    responseText,
    payload
  };
};

/**
 *
 * @param {Array} errors
 * @return {string} msgs
 * @description transforms errors generated by express validator to
 * a single message string with each message separated by '|'
 */
// transformer.transformExpressValidationErrors = (errors) => {
//   let msgs = '';

//   if (!Array.isArray(errors)) return msgs;

//   errors.forEach((item) => {
//     msgs += `${item.msg || ''} '|''`;
//   });

//   return msgs;
// };

export default transformer;
